# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaiDuMapTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaiDuMapTest
  pod 'BaiduMapKit' #百度地图SDK
  pod 'BMKLocationKit' #百度地图定位SDK
end
